//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agency.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flat()
        {
            this.Trade = new HashSet<Trade>();
        }
    
        public int FlatId { get; set; }
        public int FlatClientId { get; set; }
        public float FlatSquare { get; set; }
        public float FlatCost { get; set; }
        public string FlatAdrees { get; set; }
        public int FlatFloor { get; set; }
        public int FlatRooms { get; set; }
        public bool FlatBalcony { get; set; }
        public Nullable<int> FlatRegionId { get; set; }
        public Nullable<int> FlatStatusId { get; set; }
        public string FlatCondition { get; set; }
        public string FlatDescription { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Region Region { get; set; }
        public virtual StatusFlat StatusFlat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trade> Trade { get; set; }
    }
}
