//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agency.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trade
    {
        public int TradeId { get; set; }
        public int TradeRequestId { get; set; }
        public int TradeFlatId { get; set; }
        public System.DateTime TradeDate { get; set; }
        public int TradeStatusId { get; set; }
        public float TradeCost { get; set; }
    
        public virtual Flat Flat { get; set; }
        public virtual Request Request { get; set; }
        public virtual StatusTrade StatusTrade { get; set; }
    }
}
